### ISSUE TITLE
Dave's Week 6 feedback

### ISSUE THREAD

**Issue by DQueiser** [Malotkya/IndeProjectDemo#2]
# Design/Code Review 1

### Reviewer: Dave Queiser

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person|The Problem Statement was easy to read and understand, and it presented a very useful application. Looking forward to the final version! <br> The average person may find it a little technical.
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |The user stories in particular were very well-written, and stepped us through the app handily.
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>|All the requirements for the database were present; the database layout itself was very impressive. I learned about a few other tools which I was not aware of during the presentation.
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. <br>|I didn't look closely enough to notice any redundancies; the code I did see was concise and well documented. Again, found about a few tools I was unaware of before. I think it will be a well-running and interesting application when it is done. The code that was there (which was quite a bit) all ran cleanly and showed what the final app will look like.

**Comment by pawaitemadisoncollege** [comment]
@DQueiser The formatting here looks a bit off? This should display as a "pretty" table. Are you able to fix up? Let me know if you need help!

**Comment by DQueiser** [comment]
> @DQueiser The formatting here looks a bit off? This should display as a "pretty" table. Are you able to fix up? Let me know if you need help!

> @DQueiser The formatting here looks a bit off? This should display as a "pretty" table. Are you able to fix up? Let me know if you need help!

Got it to look a little spiffier this time.

**Comment by DQueiser** [comment]
> @DQueiser The formatting here looks a bit off? This should display as a "pretty" table. Are you able to fix up? Let me know if you need help!

**Comment by pawaitemadisoncollege** [comment]
@DQueiser Looks good thank you!
